spring:
  application:
    openApi:
      title: Citad API
      description: Citad API
      version: 1.0
      license:
        name: Apache License Version 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
      name: citad-api
      url: https://citad.com
    sftp:
      host: ${HOST}
      port: 22
      user: ${USERNAME}
      password: ${PASSWORD}
      remote-directory: /C:/Users/Administrator/Documents
      local-directory: src/main/resources/data.txt
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_SCHEMAS}
    show-sql: true

  logging:
    level:
      root: INFO
      org.springframework: INFO
      com.example: DEBUG
    path: src/main/resources/logs
    layout:
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}